### ISSUE TITLE
aternos bot not active

### ISSUE THREAD

**Issue by Adarsh-achu** [aternosorg/modbot#112]
do we need to set the google api key

**Comment by JulianVennen** [comment]
if you want to use the video/tutorial/playlist command yes. Otherwise it shouldn't be a problem if it isn't set

**Comment by Adarsh-achu** [comment]
and i followed all instructions but  the bot not active

**Comment by Adarsh-achu** [comment]
created a empty db and linked them

**Comment by JulianVennen** [comment]
Did you start the bot?
Go to the folder where you downloaded the files to and run `node bot.js`

**Comment by Adarsh-achu** [comment]
yes i did  that

**Comment by Adarsh-achu** [comment]
![Screenshot_2020-10-10-20-08-36-065_com termux](https://user-images.githubusercontent.com/71401126/95657857-725f8680-0b34-11eb-9fd2-4dcd67d40951.jpg)

**Comment by Adarsh-achu** [comment]
$ node --trace-warnings ...
internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module '/data/data/com.termux/files/home/aternos/modbot/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by JulianVennen** [comment]
To the screenshot:
make sure your mysql login data and the database name are correct

**Comment by JulianVennen** [comment]
#113 added a specific error message for invalid login credentials. if you update to that and run the bot again it should say that access to the db was denied

**Comment by Adarsh-achu** [comment]
bro thanks for your help iqm using termux its more complicated

**Comment by Adarsh-achu** [comment]
bro how to set the status channel

**Comment by Adarsh-achu** [comment]
how to set bot for showing our server details with ip

**Comment by JulianVennen** [comment]
That's not what this bot does. Modbot is a moderation bot. The server embeds on the Aternos Discord are done by a completely different bot that you cant invite or host yourself

**Comment by Adarsh-achu** [comment]
oh so this bot can't show our aternos server stats

**Comment by JulianVennen** [comment]
Nope and i have no idea how you came to that conclusion

**Comment by Adarsh-achu** [comment]
ok bro but i manged to use that bot in TERMUX

**Comment by JulianVennen** [comment]
This is not the Aternos bot.
You can run Modbot yourself but you can't run the Aternos bot.
Use something like crafty or DiscordSRV

**Comment by Adarsh-achu** [comment]
but iam on bedrock
