### ISSUE TITLE
lock command error

### ISSUE THREAD

**Issue by Salvi0** [aternosorg/modbot#231]
i updated my instance of the bot by downloading it directly from here, but when i have done my tests i found out a strange error with the command lock, both the global/id/argument give the same result.

`An error occurred while executing command lock: Error: ER_BAD_FIELD_ERROR: Unknown column 'guildid' 
in 'field list'
    at Query.Sequence._packetToError (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\salvi\Desktop\discord bots\modbot-master\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\salvi\Desktop\discord bots\modbot-master\src\Database.js:97:39
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'guildid' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: 'INSERT INTO `channels` (config,id,guildid) VALUES (\'{\\"id\\":\\"744256496677945486\\",\\"lock\\":{\\"SEND_MESSAGES\\":null,\\"ADD_REACTIONS\\":null}}\',\'744256496677945486\',\'712196984496455690\')'
}`

The main bot seems unaffected

**Comment by JulianVennen** [comment]
Did you run the update script as described in [Release 0.1.1](https://github.com/aternosorg/modbot/releases/tag/0.1.1)?

**Comment by Salvi0** [comment]
my bad noticed it just now. It fixed the issue ^^
