### ISSUE TITLE
I have an error with db

### ISSUE THREAD

**Issue by xX-Joni-Xx** [aternosorg/modbot#321]
My Code:

"db": {
    "host": "localhost",
    "user": "modbot",
    "password": "",
    "database": "modbot",
    "charset": "utf8mb4",
    "supportBigNumbers": true,
    "bigNumberStrings": true
  },

Error:

Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
    --------------------
    at Protocol._enqueue (/home/pi/modbot/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/pi/modbot/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/pi/modbot/node_modules/mysql/lib/Connection.js:116:18)
    at Database._connect (/home/pi/modbot/src/Database.js:42:16)
    at new Database (/home/pi/modbot/src/Database.js:14:14)
    at new Bot (/home/pi/modbot/src/Bot.js:36:26)
    at Function.<static_fields_initializer> (/home/pi/modbot/src/Bot.js:9:23)
    at Object.<anonymous> (/home/pi/modbot/src/Bot.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}
pi@pi4:~/modbot $ node index.js 
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
    --------------------
    at Protocol._enqueue (/home/pi/modbot/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/pi/modbot/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/pi/modbot/node_modules/mysql/lib/Connection.js:116:18)
    at Database._connect (/home/pi/modbot/src/Database.js:42:16)
    at new Database (/home/pi/modbot/src/Database.js:14:14)
    at new Bot (/home/pi/modbot/src/Bot.js:36:26)
    at Function.<static_fields_initializer> (/home/pi/modbot/src/Bot.js:9:23)
    at Object.<anonymous> (/home/pi/modbot/src/Bot.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}

**Comment by JulianVennen** [comment]
you need a mysql database. You dont have one set up

**Comment by xX-Joni-Xx** [comment]
How can i setup it?

**Comment by JulianVennen** [comment]
get a mysql database, create an account for the bot and enter the server IP and account data in the config

**Comment by xX-Joni-Xx** [comment]
Ok. Thank you very much!

**Comment by danielazulay** [comment]
https://github.com/aternosorg/modbot/issues/321#issuecomment-874861867
i Did this for me not work

Error occurred { Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
    --------------------

**Comment by JulianVennen** [comment]
do you have a mysql/mariadb server?

**Comment by danielazulay** [comment]
MYSQL80 workbrench

**Comment by JulianVennen** [comment]
Make sure the Mysql server is running and it's using port 3306.
