### ISSUE TITLE
Error: Cannot find module './config.json'

### ISSUE THREAD

**Issue by NoobCoderJJ** [aternosorg/modbot#380]
**I don't know why I am getting this error,**

`PS C:\Users\super\OneDrive\Documents\GitHub\AndroBot> node .
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../config.json'
Require stack:
- C:\Users\jane\OneDrive\Documents\GitHub\Bot\src\Monitor.js
- C:\Users\jane\OneDrive\Documents\GitHub\AndroBot\src\Database.js
- C:\Users\jane\OneDrive\Documents\GitHub\AndroBot\src\Bot.js
- C:\Users\jane\OneDrive\Documents\GitHub\AndroBot\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Function.<static_initializer> (C:\Users\super\OneDrive\Documents\GitHub\AndroBot\src\Monitor.js:9:36)
    at Object.<anonymous> (C:\Users\super\OneDrive\Documents\GitHub\AndroBot\src\Monitor.js:1:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\jane\\OneDrive\\Documents\\GitHub\\Bot\\src\\Monitor.js',
    'C:\\Users\\jane\\OneDrive\\Documents\\GitHub\\Bot\\src\\Database.js',
    'C:\\Users\\jane\\OneDrive\\Documents\\GitHub\\Bot\\src\\Bot.js',
    'C:\\Users\\jane\\OneDrive\\Documents\\GitHub\\Bot\\index.js'
  ]
}`

**Comment by matthi4s** [comment]
Please read the README, you probably missed at least step 5 of the self hosting steps.
