### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by NoobCoderJJ** [aternosorg/modbot#381]
**Error?**

`Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)
    --------------------
    at Protocol._enqueue (C:\Users\CJ\OneDrive\Documents\GitHub\Bot\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\CJ\OneDrive\Documents\GitHub\Bot\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (C:\Users\super\OneDrive\Documents\GitHub\Bot\node_modules\mysql\lib\Connection.js:116:18)      
    at new Database (C:\Users\CJ\OneDrive\Documents\GitHub\Bot\src\Database.js:21:14)
    at new Bot (C:\Users\CJ\OneDrive\Documents\GitHub\Bot\src\Bot.js:48:26)
    at Function.<static_initializer> (C:\Users\CJ\OneDrive\Documents\GitHub\Bot\src\Bot.js:11:23)
    at Object.<anonymous> (C:\Users\CJ\OneDrive\Documents\GitHub\Bot\src\Bot.js:8:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}`

**Comment by Kaluub** [comment]
See #321
