### ISSUE TITLE
Import command errors

### ISSUE THREAD

**Issue by MiataBoy** [aternosorg/modbot#570]
Upon trying to import a JSON file with modbot's exported data, at least to a server where data is already saved - it'll error.
![image](https://user-images.githubusercontent.com/34064010/236704594-29aba338-0580-4c5f-951b-87e1238395ff.png)

**Comment by JulianVennen** [comment]
The issue here seems to be one of the log channel properties:
```
Error [GuildChannelUnowned]: The fetched channel does not belong to this manager's guild.
    at GuildChannelManager.fetch (/aternos/modbot/node_modules/discord.js/src/managers/GuildChannelManager.js:385:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GuildWrapper.fetchChannel (file:///aternos/modbot/src/discord/GuildWrapper.js:118:20)
    at async ModBotImporter._importGuildConfig (file:///aternos/modbot/src/database/export/ModBotImporter.js:86:24)
    at async Promise.all (index 0)
    at async ModBotImporter.import (file:///aternos/modbot/src/database/export/ModBotImporter.js:73:9)
    at async ImportCommand.execute (file:///aternos/modbot/src/commands/bot/ImportCommand.js:84:9)
    at async CommandManager.execute (file:///aternos/modbot/src/commands/CommandManager.js:231:13)
    at async CommandEventListener.execute (file:///aternos/modbot/src/events/discord/interactionCreate/CommandEventListener.js:15:13)
```
I added a potential fix in https://github.com/aternosorg/modbot/commit/e4a3b7dfb647a42289ecdd90fe920c9b88cfc621, but I haven't tested it yet
