### ISSUE TITLE
Bot Crash Error

### ISSUE THREAD

**Issue by Rapid-Fast** [aternosorg/modbot#608]
Get this error when starting up the bot:
```Bot crashed
SyntaxError: Expected double-quoted property name in JSON at position 178
    at JSON.parse (<anonymous>)
    at readJSON (file:///home/container/src/util/fsutils.js:27:17)
    at async Config.load (file:///home/container/src/bot/Config.js:169:26)
    at async start (file:///home/container/index.js:15:5)
SyntaxError: Expected double-quoted property name in JSON at position 178
    at JSON.parse (<anonymous>)
    at readJSON (file:///home/container/src/util/fsutils.js:27:17)
    at async Config.load (file:///home/container/src/bot/Config.js:169:26)
    at async start (file:///home/container/index.js:15:5)```

**Comment by JulianVennen** [comment]
Your config is invalid JSON
